/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativePqIndex */

#ifndef _Included_com_vectordb_jni_NativePqIndex
#define _Included_com_vectordb_jni_NativePqIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativePqIndex
 * Method:    nativeCreatePQ
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_vectordb_jni_NativePqIndex_nativeCreatePQ
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_vectordb_jni_NativePqIndex
 * Method:    nativeTrain
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativePqIndex_nativeTrain
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
