/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativeHnswIndex */

#ifndef _Included_com_vectordb_jni_NativeHnswIndex
#define _Included_com_vectordb_jni_NativeHnswIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativeHnswIndex
 * Method:    nativeCreateHNSW
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_vectordb_jni_NativeHnswIndex_nativeCreateHNSW
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
