/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativeIndex */

#ifndef _Included_com_vectordb_jni_NativeIndex
#define _Included_com_vectordb_jni_NativeIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativeIndex
 * Method:    nativeAdd
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativeIndex_nativeAdd
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     com_vectordb_jni_NativeIndex
 * Method:    nativeSearch
 * Signature: (J[FI[I[F)I
 */
JNIEXPORT jint JNICALL Java_com_vectordb_jni_NativeIndex_nativeSearch
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jintArray, jfloatArray);

/*
 * Class:     com_vectordb_jni_NativeIndex
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativeIndex_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_vectordb_jni_NativeIndex
 * Method:    nativeAddBatch
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativeIndex_nativeAddBatch
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jint);

/*
 * Class:     com_vectordb_jni_NativeIndex
 * Method:    nativeSearchBatch
 * Signature: (JLjava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_vectordb_jni_NativeIndex_nativeSearchBatch
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
