/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativeAnnoyIndex */

#ifndef _Included_com_vectordb_jni_NativeAnnoyIndex
#define _Included_com_vectordb_jni_NativeAnnoyIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativeAnnoyIndex
 * Method:    nativeCreateAnnoy
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_vectordb_jni_NativeAnnoyIndex_nativeCreateAnnoy
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_vectordb_jni_NativeAnnoyIndex
 * Method:    nativeBuild
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativeAnnoyIndex_nativeBuild
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
