/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativeLshIndex */

#ifndef _Included_com_vectordb_jni_NativeLshIndex
#define _Included_com_vectordb_jni_NativeLshIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativeLshIndex
 * Method:    nativeCreateLSH
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_vectordb_jni_NativeLshIndex_nativeCreateLSH
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
