/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectordb_jni_NativeIvfIndex */

#ifndef _Included_com_vectordb_jni_NativeIvfIndex
#define _Included_com_vectordb_jni_NativeIvfIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectordb_jni_NativeIvfIndex
 * Method:    nativeCreateIVF
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_vectordb_jni_NativeIvfIndex_nativeCreateIVF
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_vectordb_jni_NativeIvfIndex
 * Method:    nativeTrain
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_com_vectordb_jni_NativeIvfIndex_nativeTrain
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
